name: Trigger auto deployment for ws-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ws-server-AutoDeployTrigger-b8430775-9e12-420c-9b2b-1f00aca245ee.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WSSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WSSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WSSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.WSSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WSSERVER_REGISTRY_PASSWORD }}
          containerAppName: ws-server
          resourceGroup: onlyfriends-api
          imageToBuild: mmpotulo28/ws-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


